version: "3.9"
services:
  backend:
    build: ./api-proxy/
    image: pizza-ordering/backend
    command: node server.js
    volumes:
      - ./api-proxy/:/usr/local/app/
    ports:
      - "5000:5000"
    environment:
      HOST: "0.0.0.0"
      PORT: 5000
  frontend:
    build: .
    image: pizza-ordering/frontend
    command: npm start
    depends_on:
      - backend
    volumes:
      - .:/app/
    ports:
      - "3000:3000"
    environment:
      REACT_APP_SERVICE_ENDPOINT: "http://localhost:5000"
